#!/usr/bin/env sh

IS_PUBLISHED_VERSION=`git describe --tags --exact-match 2>/dev/null`
MB_GRUNT_VERSION=`cat package.json | grep '"version"' | sed -E -e 's/.*"version": "([^"]*)",/\1/'`

# We don't set the version suffix on tagged (published) builds
if [ -n "$TRAVIS_BUILD_NUMBER" -a -z "$IS_PUBLISHED_VERSION" ]; then
    MB_GRUNT_VERSION="$MB_GRUNT_VERSION-beta.$TRAVIS_BUILD_NUMBER"
fi

echo "IS_PUBLISHED_VERSION: $IS_PUBLISHED_VERSION"
echo "TRAVIS_BUILD_NUMBER: $TRAVIS_BUILD_NUMBER"
echo "VERSION: $MB_GRUNT_VERSION"
npm install
grunt "$@"
